^XX^^x66x^X^x# syntax = docker/dockerfile:1

ARG RUBY_VERSION=3.3.4
FROM ruby:$RUBY_VERSION

# Install dependencies
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

# Set working directory
WORKDIR /app

# Add Gemfile and install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the main application
COPY . .

# Install jemalloc for reduced memory usage and latency
RUN apt-get update && apt-get install -y libjemalloc2
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2

# Expose port 3000
EXPOSE 3000

# Set environment variables and run commands based on environment
ARG RAILS_ENV
ENV RAILS_ENV=${RAILS_ENV}

CMD bash -c "
  if [ \"$RAILS_ENV\" = 'production' ]; then
    bundle exec rails db:migrate;
  else
    bundle exec rails db:setup;
  fi;
  rm -f tmp/pids/server.pid;
  bundle exec rails s -p 3000 -b '0.0.0.0'
"
