services:
  - type: web
    name: your-app-name
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: 'true'

  - type: postgres
    name: your-database-name
    ipAllowList: []
