services:
  - type: web
    name: your-app-name
    env: ruby
    buildCommand: bundle install
    startCommand: echo "Running in production mode" && bundle exec rails db:migrate && bundle exec rails server -p $PORT
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: 'true'

  - type: postgres
    name: your-database-name
    ipAllowList: []
