name: CI
env:
  ACTIONS_STEP_DEBUG: true

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          bundler: latest

      - name: Output Ruby and Bundler versions
        run: |
          ruby --version
          bundle --version

      - name: Install Bundler
        run: gem install bundler

      - name: Output versions
        run: |
          ruby --version
          gem --version
          bundle --version
          node --version
          npm --version

      - name: Debug bundle environment
        run: |
          gem env
          bundle env

      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3 --verbose

      - name: Scan for security vulnerabilities in Ruby dependencies
        run: bin/brakeman --no-pager --debug

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          bundler: latest

      - name: Output Ruby and Bundler versions
        run: |
          ruby --version
          bundle --version

      - name: Install Bundler
        run: gem install bundler

      - name: Debug bundle environment
        run: |
          gem env
          bundle env

      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3 --verbose

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          bundler: latest

      - name: Output Ruby and Bundler versions
        run: |
          ruby --version
          bundle --version

      - name: Install Bundler
        run: gem install bundler

      - name: Debug bundle environment
        run: |
          gem env
          bundle env

      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3 --verbose

      - name: Lint code for consistent style
        run: bin/rubocop -f github --extra-details --display-cop-names

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

      # redis:
      #   image: redis
      #   ports:
      #     - 6379:6379
      #   options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client postgresql-client

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          bundler: latest

      - name: Output Ruby and Bundler versions
        run: |
          ruby --version
          bundle --version

      - name: Install Bundler
        run: gem install bundler

      - name: Debug bundle environment
        run: |
          gem env
          bundle env

      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler
          bundle install --jobs 4 --retry 3 --verbose

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
          # REDIS_URL: redis://localhost:6379/0
          RUBY_DEBUG: 1
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

      - name: Check PostgreSQL connection
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c '\conninfo'

  validate_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Validate commit messages
        env:
          NODE_DEBUG: '*'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
